name: Generate Datas

on:
  schedule:
    # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    # Add permissions for the GITHUB_TOKEN
    permissions:
      contents: write
      pages: write # Required for deployment
    steps:
      # Checkout the repository (necessary for context and potential existing files)
      - uses: actions/checkout@v4

      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: rory-mendez
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy to the output branch
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4 # Use version 4 for better compatibility/support
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
